
CREATE DATABASE `runninghill` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `words` (
  `wordID` int NOT NULL AUTO_INCREMENT,
  `word` varchar(250) NOT NULL,
  `Wordtype` varchar(50) NOT NULL,
  PRIMARY KEY (`wordID`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `sentence` (
  `sentenceID` int NOT NULL AUTO_INCREMENT,
  `sentence` varchar(500) DEFAULT NULL,
  `EntryDate` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`sentenceID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
